apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mathtrail

# Default: deploy everything
requires:
  - configs:
      - all-infra
      - all-services

---
# ── Aggregate modules ─────────────────────────────────────────

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: all-infra

requires:
  - configs:
      - infra
  - configs:
      - infra-local
      - infra-observability
      - infra-testing
      - infra-chaos

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: all-services

requires:
  - configs:
      - identity
      - mentor
      - profile

---
# ── Infrastructure ────────────────────────────────────────────

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra

requires:
  - path: ../mathtrail-infra

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-local

requires:
  - path: ../mathtrail-infra-local

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-observability

requires:
  - path: ../mathtrail-infra-observability

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-testing

requires:
  - path: ../mathtrail-infra-testing

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-chaos

requires:
  - path: ../mathtrail-infra-chaos

---
# ── Services ──────────────────────────────────────────────────

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: identity

requires:
  - path: ../mathtrail-identity

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mentor

requires:
  - path: ../mathtrail-mentor

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: profile

requires:
  - path: ../mathtrail-profile
