apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: mathtrail-remote

# Default: deploy everything
requires:
  - git:
      repo: https://github.com/MathTrail/mathtrail-infra
      path: skaffold.yaml
      ref: main
  - git:
      repo: https://github.com/MathTrail/mathtrail-infra-local
      path: skaffold.yaml
      ref: main
  - git:
      repo: https://github.com/MathTrail/mathtrail-infra-testing
      path: skaffold.yaml
      ref: main
  - git:
      repo: https://github.com/MathTrail/mathtrail-identity
      path: skaffold.yaml
      ref: main
  - git:
      repo: https://github.com/MathTrail/mathtrail-mentor
      path: skaffold.yaml
      ref: main
  - git:
      repo: https://github.com/MathTrail/mathtrail-profile
      path: skaffold.yaml
      ref: main

profiles:
  # ── Infrastructure ───────────────────────────────────────────
  - name: infra
    patches:
      - op: replace
        path: /requires
        value:
          - git:
              repo: https://github.com/MathTrail/mathtrail-infra
              path: skaffold.yaml
              ref: main

  - name: infra-local
    patches:
      - op: replace
        path: /requires
        value:
          - git:
              repo: https://github.com/MathTrail/mathtrail-infra-local
              path: skaffold.yaml
              ref: main

  - name: infra-testing
    patches:
      - op: replace
        path: /requires
        value:
          - git:
              repo: https://github.com/MathTrail/mathtrail-infra-testing
              path: skaffold.yaml
              ref: main

  # ── Services ─────────────────────────────────────────────────
  - name: mentor
    patches:
      - op: replace
        path: /requires
        value:
          - git:
              repo: https://github.com/MathTrail/mathtrail-mentor
              path: skaffold.yaml
              ref: main

  - name: identity
    patches:
      - op: replace
        path: /requires
        value:
          - git:
              repo: https://github.com/MathTrail/mathtrail-identity
              path: skaffold.yaml
              ref: main

  - name: profile
    patches:
      - op: replace
        path: /requires
        value:
          - git:
              repo: https://github.com/MathTrail/mathtrail-profile
              path: skaffold.yaml
              ref: main

  # ── Combined ─────────────────────────────────────────────────
  - name: all-infra
    patches:
      - op: replace
        path: /requires
        value:
          - git:
              repo: https://github.com/MathTrail/mathtrail-infra
              path: skaffold.yaml
              ref: main
          - git:
              repo: https://github.com/MathTrail/mathtrail-infra-local
              path: skaffold.yaml
              ref: main
          - git:
              repo: https://github.com/MathTrail/mathtrail-infra-testing
              path: skaffold.yaml
              ref: main

  - name: all-services
    patches:
      - op: replace
        path: /requires
        value:
          - git:
              repo: https://github.com/MathTrail/mathtrail-identity
              path: skaffold.yaml
              ref: main
          - git:
              repo: https://github.com/MathTrail/mathtrail-mentor
              path: skaffold.yaml
              ref: main
          - git:
              repo: https://github.com/MathTrail/mathtrail-profile
              path: skaffold.yaml
              ref: main

