---
- name: Base infrastructure
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - role: mathtrail.infra.docker
    - role: mathtrail.infra.helm
    - role: mathtrail.infra.kubectl
