name: 'MathTrail Setup Environment'
description: 'Loads variables via git checkout'

runs:
  using: "composite"
  steps:
    - name: Checkout Platform Config
      uses: actions/checkout@v4
      with:
        repository: MathTrail/core
        # github.action_ref points to the tag or branch used to call this action (e.g., @v1 or @v1.2.3)
        # This ensures the config file version matches the action version.
        ref: ${{ github.action_ref }}
        path: .temp-platform-core
        sparse-checkout: |
          platform-env/global.env
        sparse-checkout-cone-mode: false
        token: ${{ github.token }}

    - name: Load Variables
      shell: bash
      run: |
        cat .temp-platform-core/platform-env/global.env >> $GITHUB_ENV
        rm -rf .temp-platform-core
