name: 'MathTrail Setup Environment'
description: 'Loads variables via git checkout'

inputs:
  version:
    description: 'Version of the config to pull (tag or branch)'
    required: false
    # By default, we try to use the ref the action itself was called with
    default: ${{ github.action_ref }}

runs:
  using: "composite"
  steps:
    - name: Checkout Platform Config
      uses: actions/checkout@v4
      with:
        repository: MathTrail/core
        # We use the input version, which defaults to the action's own ref
        ref: ${{ inputs.version }}
        path: .temp-platform-core
        sparse-checkout: |
          platform-env/global.env
        sparse-checkout-cone-mode: false
        token: ${{ github.token }}

    - name: Load Variables
      shell: bash
      run: |
        cat .temp-platform-core/platform-env/global.env >> $GITHUB_ENV
        rm -rf .temp-platform-core
